language: node_js
node_js:
- '0.12'
- '0.11'
- '0.10'

services:
  - mongodb
# addons:
#   apt:
#     sources:
#     - mongodb-3.0-precise
#     packages:
#     - mongodb-org-server

branches:
  only:
  - master
before_script:
  - set -e
  - npm install
  - npm run build
  - npm migrate
script:
  - npm test
